### ISSUE TITLE
Only the first profile in list is plotted 

### ISSUE THREAD

**Issue by Faride-Dm** [dmentipl/plonk#30]
I am using Plonk to make a profile plot and I have a problem with that. After reading the list of profiles and appending them, only the first snap is plotted. 

plonk version: 0.7.3
python: 3.7.4
Linux mint 18.1
jupyter lab

```python
import plonk
import matplotlib.pyplot as plt
import numpy as np

filename = 'file_address'
snap = plonk.load_snap(filename)

snap = plonk.load_snap(filename)
snap.add_quantities('disc')
prof = plonk.load_profile(snap, cmin='10 au', cmax='200 au')

snap['timestep'].to('Myr')

snap['x'].to('pc')

sim = plonk.load_simulation(prefix='disc')

sinkFilePath = !ls 'my sink_file_path'

times = sim.properties['time'].to('Myr')

for sinklist in sinkFilePath:
    print(sinklist)
    profiles = list()
    snap = plonk.load_snap(sinklist)
    profile = plonk.load_profile(snap, cmin='10 au', cmax='150 au', n_bins=50)
    profiles.append(profile)

fig, ax = plt.subplots()
units = {'position': 'pc', 'density': 'g/cm^3'}
for time, profile in zip(times, profiles):
    label = f'{time.m:.0f}'
    profile.plot(
        'radius', 'density', units=units, label=label, ax=ax
    )
ax.set_ylabel('Density [g/cm${}^3$]')
ax.legend(title='Time [Myr]', loc='best')
```

I also need to plot multiple snapshots in a single panel. I used to do it with splash and I want to know if it is possible in plonk. I expect a plot similar to what splash produces. 
[multiple_plot.pdf](https://github.com/dmentipl/plonk/files/5304764/multiple_plot.pdf)

**Comment by dmentipl** [comment]
Hi @Faride-Dm, thanks for raising this issue.

Unfortunately, I don't have time at the moment to respond as I'm writing up my PhD thesis. Hopefully, I'll have more time in December, or January next year.

**Comment by Faride-Dm** [comment]
Hi Daniel,

Thanks for letting me know about the approximate time. Good luck with your
thesis.

Regards,

Faride

**Comment by dmentipl** [comment]
Hi @Faride-Dm, sorry for the long delay in response. (I've since finished my PhD and started a new job.)

I'm not entirely sure what you would like to do with multiple profiles. There is an example in the docs: see [here](https://plonk.readthedocs.io/en/stable/examples/density-profiles.html). Let me know if that is what you're looking for. Hopefully that helps.

With regards to plotting multiple snaps in a single panel there is [this](https://plonk.readthedocs.io/en/stable/examples/deviation-from-keplerian.html) example in the docs. Let me know if that helps. (It's a little complicated but the essence of what you're doing is there.) Let me know if that helps.

**Comment by dmentipl** [comment]
Hi @Faride-Dm, I'm going to close this issue. Please feel free to re-open if you still need some help 😄
